[workspace]
members = [
  "zomes/numbers",
  "zomes/whoami",
  "zomes/squareroots",
  "zomes/pcrtests",
  "zomes/holotokens",
  "zomes/tradingprices",  
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
